### PR TITLE
Prateekheatmap

### PR DESCRIPTION
**Pull request by prateek1095**
I made some changes.please review.
Added an alert modal when user doesn't input the query field.
Added pro tip bars that closes automatically.

### CODE REVIEW

**Comment by jigyasa-grover** [comment]
@prateek1095 , two cents
1. Always submit a single commit for a single issue resolved
2. The commit message should lucidly explain the purpose of the PR
3. Also there seem to be merge conflicts in there, kindly resolve them

**Comment by prateek1095** [comment]
@jig08 ,
Thanks for the advice , due to some unforced error some unwanted things were added. Now removed and resolved. some changes are made:
1.An alert modal bar added which pops up if a user clicks on search button without entering any query.
2. 2 'pro tip bar' added which closes automatically after some time.

**Comment by jigyasa-grover** [comment]
@prateek1095 Kindly squash all the commits and make the commit message indicative enough.

**Comment by prateek1095** [comment]
I have squashed all the commits.
Please review.

**Comment by sevazhidkov** [comment]
Hm, something wrong with pull request, please, send it again

**Pull request closed without merging**
